docker rm master
docker rm mysqlserver
docker rm webserver
docker run \
     -d \
     --name master \
     --publish=7474:7474 --publish=7687:7687 \
     --volume=$HOME/neo4j/data:/data \
     --volume=$HOME/neo4j/logs:/logs \s
     --user="$(id -u):$(id -g)" \
     neo4j:latest


docker run \
  -d \
  --name mysqlserver \
  -e MYSQL_ROOT_PASSWORD=root \
  mysql


docker run \
  -d \
  --publish=8083:80 \
  --name webserver \
  --volume=/home/aimen/MyWorkspace/corona-virus-world-mater/graph-front/src/main/resources:/usr/share/nginx/html \
nginx
